name: speedest_logistics
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  appwrite: ^4.0.1
  loading_indicator: ^3.0.3
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  flutter_font_icons: ^2.2.4
  flutter_typeahead: ^3.2.4
  flutter_native_splash: ^2.1.6
  json_serializable: ^6.1.6
  intl: ^0.17.0
  qr_code_scanner: ^1.0.0-alpha.1
  firebase_core: ^1.14.1
  firebase_messaging: ^11.2.13
  osm_nominatim: ^2.0.1
  timelines: ^0.1.0
  qr_flutter: ^4.0.0
  screenshot: ^1.2.3
  esys_flutter_share_plus: ^2.1.0
  flutter_local_notifications: ^9.4.1
  flutter_ringtone_player: ^3.2.0
  flutter_osm_plugin: ^0.33.0+2
  flutter_map: ^0.14.0
  flutter_map_marker_cluster: ^0.4.4
  equatable: ^2.0.3
  background_locator:
    git:
      url: https://github.com/caiobraga/background_locator.git
  get_storage: ^2.0.3
  location_permissions: ^4.0.1
  path_provider_android: ^2.0.12
  path_provider_ios: ^2.0.8
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  bloc_test: ^9.0.3
  flutter_launcher_icons: "^0.9.2"
  build_runner: ^2.1.10

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/speed_log_icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
